version: "3"

networks:
  iamcare-network:
    driver: bridge

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - APP_DEBUG=${API_DEBUG:-true}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - GOOGLE_PLACES_COUNTRY_CODE=${GOOGLE_PLACES_COUNTRY_CODE}
      - SANCTUM_STATEFUL_DOMAINS=${API_STATEFUL_DOMAIN:-localhost:7222}
      - SESSION_DOMAIN=${API_COOKIE_DOMAIN:-localhost}
    networks:
      - iamcare-network
    ports:
      - "9222:8000"
    volumes:
      - ./api/logs/php.log:/var/log/fpm-php.www.log
    x-develop:
      watch:
        - action: sync
          ignore:
            - .phpunit.cache/
            - logs/
            - vendor/
          path: ./api
          target: /var/www/html

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - api
    environment:
      - API_BASE_URL=${CLIENT_API_BASE_URL:-/api}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - GOOGLE_PLACES_COUNTRY_CODE=${GOOGLE_PLACES_COUNTRY_CODE}
      - PORT=3000
    networks:
      - iamcare-network
    ports:
      - "7222:3000"
    x-develop:
      watch:
        - action: sync
          ignore:
            - .parcel-cache/
            - coverage/
            - dist/
            - node_modules/
          path: ./client
          target: /home/node/application/app
        - action: rebuild
          path: ./client/package.json

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-iamcare}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER:-iamcare}
    networks:
      - iamcare-network
    volumes:
      - ./database/data:/var/lib/mysql

  database-testing:
    build: ./database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-iamcare}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER:-iamcare}
    networks:
      - iamcare-network
