version: "3"

networks:
  iamcare-network:
    driver: bridge

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          ignore:
            - .phpunit.cache/
            - composer.json
            - composer.lock
            - logs/
            - storage/
            - vendor/
          path: ./api
          target: /var/www/html
    environment:
      - APP_DEBUG=${API_DEBUG:-true}
      - APP_NAME=${API_APPLICATION_NAME:-iamcare}
      - APP_URL=${API_URL:-http://localhost:7222}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL:-http://localhost:7222}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - GOOGLE_PLACES_COUNTRY_CODE=${GOOGLE_PLACES_COUNTRY_CODE}
      - LOG_LEVEL=${API_LOG_LEVEL:-debug}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-iamcare}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - SANCTUM_STATEFUL_DOMAINS=${API_STATEFUL_DOMAIN:-localhost:7222}
      - SESSION_DOMAIN=${API_COOKIE_DOMAIN:-localhost}
    networks:
      - iamcare-network
    ports:
      - "9222:8000"
    volumes:
      - ./api/composer.json:/var/www/html/composer.json
      - ./api/composer.lock:/var/www/html/composer.lock
      - ./api/logs/php.log:/var/log/fpm-php.www.log
      - ./api/storage/:/var/www/html/storage

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          ignore:
            - .parcel-cache/
            - package-lock.json
            - package.json
            - coverage/
            - dist/
            - node_modules/
          path: ./client
          target: /home/node/application/app
    environment:
      - API_BASE_URL=${CLIENT_API_BASE_URL:-/api}
      - GITHUB_URL=${GITHUB_URL:-https://github.com/hvolschenk/iamcare}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - GOOGLE_PLACES_COUNTRY_CODE=${GOOGLE_PLACES_COUNTRY_CODE}
      - PORT=3000
    networks:
      - iamcare-network
    ports:
      - "7222:3000"
    volumes:
      - ./client/package-lock.json:/home/node/application/app/package-lock.json
      - ./client/package.json:/home/node/application/app/package.json

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-iamcare}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER:-iamcare}
    networks:
      - iamcare-network
    volumes:
      - ./database/data:/var/lib/mysql

  database-testing:
    build: ./database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-iamcare}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER:-iamcare}
    networks:
      - iamcare-network
