name: CD
on:
  push:
    branches:
      - main

jobs:
  netherlands:
    name: Netherlands
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: NETHERLANDS
      url: https://ikbenzorg.nl

  south_africa:
    name: South Africa
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: SOUTH_AFRICA
      url: https://iamcare.co.za
